name: Check Next.js site deployability

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "master" ]
  # Runs on pull requests targeting the default branch
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Build with Next.js
        run: npx next build
